### ISSUE TITLE
Implement clearer design of content area of wall

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#330]
Let's follow some sample services for the wall and implement a clearer content area.

![screenshot from 2015-07-09 16 48 24](https://cloud.githubusercontent.com/assets/1583873/8598366/8d9243d0-265a-11e5-8c75-262606d0d5df.png)

Please also add buttons/areas for features coming soon. Please make them show up, but also make them grey and add "coming soon" behind them.

**Comment by aneeshd16** [comment]
@Orbiter this is how the wall creation modal looks now. What should be the appropriate query for this? Since there is only 1 object in the "Any of these" fields, that object should be optional. Tweets may or may not contain that. But if there is only 1 object, what will it be ORred with?
![image]https://files.gitter.im/loklak/JkIA/blob)

**Comment by Orbiter** [comment]
I like this new design! The query term would be easy to construct. Consider you have:
All of these: A B C
Any of these: D E F
None of these: G H I

Then the query you must construct would be simply `A B C D OR E OR F -G -H -I`
The query parser considers OR stronger than AND which would result in the logic:
`A AND B AND C AND (D OR E OR F) AND (NOT G) AND  (NOT H) AND (NOT I)`
I believe this is also identical to "what the user means".

In case that you onl have a single term in "Any of these": just append that term, no OR anywhere.
Example:
All of these: A
Any of these: B
should construct the term `A B`.

**Comment by aneeshd16** [comment]
Awesome. Thanks!

**Comment by mariobehling** [comment]
Please also add buttons/areas for features coming soon. Please make them show up, but also make them grey and add "coming soon" behind them.
* [ ] Cycle/Repeat Tweets
* [ ] Block tweets with profanity
* [ ] Block retweets
* [ ] Hide retweets
* [ ] Follower threshold 
* [ ] Moderation

Please add helper text and "coming soon" to each point
* [ ] helper text

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8765709/4a9de8aa-2e38-11e5-8796-8b369ee55ca9.png)

**Comment by Orbiter** [comment]
I like the profanity / retweet / hide option but how are those features implemented? I guess this is the task of the server, but then we must negotiate a protocol extension. I believe that this feature is incomplete as long as we don't know how the new options are implemented. Please write down what happens if the options are selected.

**Comment by mariobehling** [comment]
@aneeshd16 Yes, please follow up on how to implement this. As mentioned, 
* [ ] please make the font of the non-existing feature Grey and 
* [ ] add in front "Coming soon"
* [ ] Please make use of the white space (behind the yes/no button). Why don't you use the whole area and spread the text more? I wish you would see these kind of things yourself.

**Comment by aneeshd16** [comment]
Done.
![image](https://cloud.githubusercontent.com/assets/5436027/8791807/5574688a-2f7d-11e5-8c68-7a3984e998e9.png)

**Comment by aneeshd16** [comment]
@Orbiter, correct. That functionality does not exist on the server yet. I will follow it up in separate issues.

**Comment by Orbiter** [comment]
Thats good. I believe those filters will be trittered with our typical constraint schema, like `-/profanity` to exclude profanity. Please open separate feature issues at loklak_server for each required filter.

**Comment by mariobehling** [comment]
Not sure, why you mark "Cycle/Repeat Tweets" as solved. I am not seeing this feature.

**Comment by mariobehling** [comment]
![5574688a-2f7d-11e5-8c68-7a3984e998e9](https://cloud.githubusercontent.com/assets/1583873/8797946/3590c55a-2f9f-11e5-874d-ee6f24245ada.png)
* [ ] Keep design in line
* [ ] Make better use of space and expand areas

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8807837/9d65d6e0-2ffc-11e5-8d90-c1d42e6ca22b.png)

**Comment by mariobehling** [comment]
Looks good!

Please show us the cycle tweet feature as well.

**Comment by aneeshd16** [comment]
Sorry, missed that :smile: 
![image](https://cloud.githubusercontent.com/assets/5436027/8819041/dcaadbd4-3065-11e5-8653-c0231bb17d93.png)

**Comment by mariobehling** [comment]
Currently deployed version is still missing this commit.

**Comment by aneeshd16** [comment]
True, I will be opening a PR as soon as the current PR is merged.

**Comment by Orbiter** [comment]
I just added the definition how to add / hide retweets, for details please see https://github.com/loklak/loklak_server/issues/81
You can implement the given rule independently of the development status of https://github.com/loklak/loklak_server/issues/81
- if 'Hide retweets' is set to NO: add the term `include:retweets` to the search terms
- if 'Hide retweets' is set to YES: do not modify the search terms - retweets are excluded by default.

**Comment by aneeshd16** [comment]
Added `include:retweets` when "Block retweets" is set to "No". Can be tested on live.

**Comment by Orbiter** [comment]
I have to re-open this issue because the wall is currently not able to make a query like "#vds OR vorratsdatenspeicherung". The reason is, that the main hashtag is always made AND by default with all other query attributes, whatever they are. If you currently enter '#vds' as main hashtag and 'vorratsdatenspeicherung' as 'Any of these words', then the resulting query is "#vds vorratsdatenspeicherung" but what the user wants is  "#vds OR vorratsdatenspeicherung".

Entering "#vds vorratsdatenspeicherung" in "Any of these words" would not solve the problem because the currently implemented Algorithm alway adds the main hashtag in conjunction with all other query attributes and the result is then "#vds #vds OR vorratsdatenspeicherung", which is, according to my investigations in https://github.com/loklak/loklak_webclient/issues/347#issuecomment-120930534 equal to "#vds AND (#vds OR vorratsdatenspeicherung)" which in turn is logical equal to 
"#vds AND vorratsdatenspeicherung". And that was not intended.

The problem would have been solved already if my recommendation in https://github.com/loklak/loklak_webclient/issues/305#issuecomment-119548696 -- plus according to the new design of this issue, filling the main hashtag in the "Any of these" field by default.

I reopen this issue to document that the following change is required:
- the main hashtag shall be filled into the field "Any of these" by default
- the default conjunction of the main hashtag with the other query attributes must be removed
