### ISSUE TITLE
Implement "Account" Search and show accounts as in twitter

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#426]
The account search currently works different to twitter. Please discuss what is required to change that to the same way and implement it.

**Comment by fuksi** [comment]
The way I'm implementing this:
- Do a normal search
- Gather all the accounts (screen_name)
- For each of the accounts, make a request to user servlet for detailed information (including banner picture, description, etc... in order to make it like twitter)

Currently I don't see user servlet blocking consecutive requests. However this is bad practice and unnecessary heavy on the server

Possible enhancement from the server: aggregation request from user servlet, for example
`http:://localhost:9000/api/user.json?screen_name=user1,user2,user3`. 

Comparing rendering time with/without enhancement:
- Without: I'm assuming request for only one user info at a time will result in the client rendering the response one at a time. Which is better experience
- With enhancement: requesting for 50 accounts' info can take longer time, however when we got a response, all will be rendered immediately. 

@Orbiter, do you think  this enhancement necessary?

**Comment by Orbiter** [comment]
I will implement an aggregated request/response for this as you suggested.
Please consider that then you don't get a 'user' object but a 'users' object containing a list of user objects.
I won't have time today as I am traveling but I can do that tomorrow.

**Comment by Orbiter** [comment]
just implemented this: https://github.com/loklak/loklak_server/commit/a261a98776b5fef92b61891ad64f4c4829d8acde which means its working now as you suggested with multi-requests. Try http://localhost:9000/api/user.json?screen_name=loklak_app,0rb1t3r,aneeshd16,lklknt,tldr42,loklak_tune

**Comment by fuksi** [comment]
It's nice the that responding time is not at all slower than retrieving info from one user. Also thank you for making it  an array but only when screen_name has many values :)

Fixed and deployed on live: https://github.com/loklak/loklak_webclient/commit/2cf4d0290cafb8406e65ff65cf674917b3892f6f

**Comment by mariobehling** [comment]
The search results of twitter are still very different to loklak, e.g compare

1) http://loklak.net/search?q=loklak%2B%2Faccounts
2) https://twitter.com/search?f=users&q=loklak

It seems loklak displays results with a different set of parameters including:
* search term has been mentioned on timeline

An additional question is: Can we implement a relevance sorting here? E.g. display results that have the search term in the name or user name should be higher than those in the description.
