### ISSUE TITLE
Add Tweets of Accounts "Following" to the Map View

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#453]
* [ ] The map view should display the last 50 tweets of the accounts the user follows. What icon should we use here? Probably the same icon (orange point) as in the search?
* [ ] The map view also has a relation to the activity bar. As the user scrolls down and more tweets are loaded the tweets that show up in the activity bar are also loaded with their location onto the map.
* [ ] In the top bar take out "Map". This is merged with the "Home" view.
* [ ] In order to show tweets on the map, the user needs to have the option "Activity Feeds" enabled. See screenshot top left.

![screenshot from 2015-08-11 14 45 14](https://cloud.githubusercontent.com/assets/1583873/9198813/0092ceec-403f-11e5-9180-06828e4e7ef1.png)

**Comment by fuksi** [comment]
This will take longer than expect since feeds from Twitter Api doesn't include geo location, however I might have found an alternative approach:
- The location of the feed will the based on the location of user (remember exceptions for user without location)
- The location is in place form: 
![image](https://cloud.githubusercontent.com/assets/6878677/9404216/33ae5b8e-47f6-11e5-8a77-118429727cf5.png), gather all of the locations and use `geocode.json` to get the location marks. Make sure there is a system to correlate the result with the feed accurately.
- Find a way to inject the layer of feeds to the current map, hide it as default

**Comment by mariobehling** [comment]
Hang on: This is supposed to be based on loklak, not on the twitter-API, just like in loklak search on the map, e.g. http://loklak.net/search?q=loklak%2B%2Fmap

It should be implemented in the same way. If there is a blocker that you depend on the server, please mention it here and move this to a later milestone.

**Comment by fuksi** [comment]
Hmm, I think the blocker will be there for a long time, since it's a lot of work https://github.com/loklak/loklak_server/issues/94 

I also thought of another approach, which is closer to the Loklak API
- We still using the hello.js (twitter API), but just to get the `id_str` from each of the feed
- Use that `id_str` to get content, along with location from loklak API, since I just discovered, this kind of query works [id:634644890337562624 OR id:634641497128857600 OR id:633745957343989761 OR id:634645753294663680](http://localhost:9000/api/search.json?timezoneOffset=-180&q=id%3A634644890337562624+OR+id%3A634641497128857600+OR+id%3A633745957343989761+OR+id%3A634645753294663680)

Later when server supports this feature, we can just eliminate the step 1.

**Comment by mariobehling** [comment]
Using only `id_str` this will mean we will show the actual tweets from loklak though?

**Comment by fuksi** [comment]
That's true. (The result of the query above, http://pastebin.com/5Qh8KpQL )

Should I go through with this approach?

**Comment by mariobehling** [comment]
Yes, this sounds like a very nice temporary solution. Once loklak offers the stream info as well, we can switch completely.

**Comment by fuksi** [comment]
Some basic implementation are included in the working branch:

Blocker isssue is defined: https://github.com/loklak/loklak_server/issues/119
Let's continue with this when Michael is back:

**Comment by Orbiter** [comment]
as https://github.com/loklak/loklak_server/issues/119 is not a bug, we should solve this using the implementation of https://github.com/loklak/loklak_server/issues/94
